config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: 'developers#index'
 resources :developers
 resources :projects
 resources :assignments
  # resources :developers, shallow: true do
  #   resources :projects, shallow: true
  # end
  #
  # resources :projects, shallow: true do
  #   resources :developers, shallow: true
  # end

  get "/projects/:project_id/developers", to: "developers#index" ,as: "devsassigned"
  get "/projects/:project_id/assignment/new", to: "assignments#new", as: "assginnew"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :developer
  belongs_to :project
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :projects, through: :assignments
  has_many :assignments, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :developers, through: :assignments
  has_many :assignments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def index
    @assigns = Assignment.all
    @assign_detail = []
    @assigns.each do |a|
      h = {:developer=> Developer.find(a.developer_id), :project=> Project.find(a.project_id)}
      @assign_detail.push(h)
    end
  end

  def show
    @project = Project.find(params[:id])
    @devs = @project.developers
  end

  def new
    @assign = Assignment.new
    @all_devs = Developer.all
    @project = Project.find(params[:project_id])
    @assign_devs = @project.developers
  end


  def create
    @assign= Assignment.new(assign_params)
    if @assign.save
       flash[:success]="New assignment created"
       redirect_to devsassigned_path(@assign.project_id)
     else
       flash[:error]="Failed creating the assignment"
       redirect_to :back
     end
  end

  private

  def assign_params
    params.require(:assignment).permit(:developer_id,:project_id)
  end

end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController


  def new
    @dev = Developer.new
  end
  def create
      @dev = Developer.new(developer_params)
      if @dev.save
        flash[:success]="New member added"
        redirect_to developers_url
      else
        flash[:error]="Fialed adding new member ... please try again"
        redirect_to :back
      end
  end
  def index
    @devs = params[:project_id] ? Project.find(params[:project_id]).developers : Developer.all
  end

  def show
     @dev = Developer.find(params[:id])
     assignments = Assignment.where(developer_id:@dev.id)
     @projects =[]
     assignments.each do |assign|
       @projects << Project.find(assign.project_id)
     end
  end

  def edit
     @dev = Developer.find(params[:id])
  end

  def update
    @dev = Developer.find(params[:id])
    @dev.update_attributes(developer_params)
    if @dev.save
      flash[:success] = "Successful update"
      redirect_to developers_url
    else
      flash[:error] = "Failed update...please try again"
      redirect_to :back
    end
  end

  def destroy
    @dev= Developer.find(params[:id])
    if @dev.destroy
      flash[:success]="Successfully removed developer from the team"
      redirect_to developers_url
    else
      flash[:error]="failed removing developer from the team... please try again"
      redirect_to :back
    end
  end


  private

  def developer_params
    params.require(:developer).permit(:first_name, :last_name, :email , :years_experience)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
  end

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "Successfully added the new project"
      redirect_to projects_url
    else
      flash[:error]="Failed at adding the new project"
      redirect_to :back
    end
  end

  private

  def project_params
    params.require(:project).permit(:name,:desc,:deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/assignments/index.html.erb
<h3> All Assignments </h3>
<hr>
<% @assign_detail.each do |ad| %>
   <p><b>Project Id:</b><%= ad[:project].id %></p>
   <p><b>Project Name: </b><%= ad[:project].name %></p>
   <p><b>Description:</b> <%= ad[:project].desc %></p>
   <p><b>Deadline: </b><%= ad[:project].deadline %> </p>
   <p><b>Developer</b><%= ad[:developer].first_name %><%= ad[:developer].last_name %></p>
   <hr>
<% end %>

app/views/assignments/new.html.erb
<h3> Adding new developer to <%= @project.name %></h3>


<% @assign_devs.each do |ad| %>
  <%= ad.first_name %>
  <%= ad.last_name %>
<% end %>


<%= form_for @assign do |f| %>
  <p> Project id: </p>
  <%= f.number_field  :project_id , :value =>@project.id %>
  <p> Developer id: </p>
  <%= f.number_field  :developer_id  %>
  <%= f.submit "Add new developer", class: "btn btn-primary" %>
<% end %>

app/views/assignments/show.html.erb
<h3> Devs assigned to <%= @project.name %> project </h3>
<% @devs.each do |d| %>
  <p> Name: <%= d.first_name %> <%=d.last_name %> </p>
<% end %>

app/views/developers/edit.html.erb
<h3> Editing <%= @dev.first_name %>'s info </h3>

<%= form_for @dev  do |f| %>
  <p> Firstname: </p>
  <%= f.text_field  :first_name  %>
  <p> Lastname: </p>
  <%= f.text_field  :last_name %>
  <p> Email: </p>
  <%= f.email_field :email %>
  <p> Years of experience </p>
  <%= f.number_field :years_experience %>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

<div>
  <a href="/" class="btn btn-default">Cancel</a>
</div>

app/views/developers/index.html.erb
<h2> Developers on the team </h2>
<table>
      <thead>
        <tr>
            <th data_field="id">ID </th>
            <th data-field="name">Name</th>
            <th data-field="email">Email</th>
            <th data-field="extra">link</th>
        </tr>
      </thead>

      <tbody>
<% @devs.each do |dev| %>
  <tr>
   <%= render  partial: "partials/dev_item", locals: {developer: dev} %>
  </tr>
<% end %>
</tbody>
</table>

app/views/developers/new.html.erb
<h3> Add new Developer </h3>


<%= form_for @dev do |f| %>
  <p> Firstname: </p>
  <%= f.text_field  :first_name  %>
  <p> Lastname: </p>
  <%= f.text_field  :last_name %>
  <p> Email: </p>
  <%= f.email_field :email %>
  <p> Years of experience </p>
  <%= f.number_field :years_experience %>
  <%= f.submit "Add new developer", class: "btn btn-primary" %>
<% end %>

<div>
  <a href="/" class="btn btn-default">Cancel</a>
</div>

app/views/developers/show.html.erb
<h3> <%= @dev.first_name %>'s Profile </h3>
<p>Years of experience: <%= @dev.years_experience %> </p>

<h4> Project List </h4>
<ol>
<% @projects.each do |p| %>
<li>  <p>Name: <%= p.name %> </p>
  <p>Desc: <%= p.desc %> </p>
</li>
<% end %>
</ol>
<%= link_to "Edit info", edit_developer_url(@dev.id) %>
<%= link_to "Remove from the team", developer_url(@dev.id) , method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Operations</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:success] %>
      <%= flash[:error] %>
    <%= render "partials/navbar" %>
    <%= yield %>
    <%= render "partials/footer" %>
  </div>
  </body>
</html>

app/views/partials/_dev_item.html.erb
<td> <%= developer.id %></td>
<td> <%= developer.first_name %> <%= developer.last_name %> </td>
<td> Email: <%= developer.email %> </td>
<td><%= link_to "info", developer_url(developer.id) %></td>

app/views/partials/_footer.html.erb
<footer>
  <hr>  
  <p class="small-grey"> ControllRoom App </p>
</footer>

app/views/partials/_navbar.html.erb
<nav>
  <span class="logo"> ControllRoom </span>
  <%= link_to "Devs | " , developers_url, class:"add_link" %>
  <%= link_to "Projects | " , projects_url, class:"add_link" %>
   <%= link_to "+Dev | " , new_developer_url, class:"add_link" %>
  <%= link_to "+Project | ", new_project_url , class:"add_link" %>
</nav>

app/views/projects/index.html.erb
<h3> All Porjects </h3>
<hr>
<% @projects.each do |project| %>
   <p><b>Project Id:</b><%= project.id %></p>
   <p><b>Project Name: </b><%= project.name %></p>
   <p><b>Description:</b> <%= project.desc %></p>
   <p><b>Deadline: </b><%= project.deadline %> </p>
   <%= link_to "assigned Devs" ,devsassigned_url(project.id) %> |
   <%= link_to "+dev to this project" , assginnew_path(project.id) %>
   <hr>
<% end %>

app/views/projects/new.html.erb
<h3> Add new Project </h3>
<%= form_for @project do |f| %>
  <p> Name: </p>
  <%= f.text_field  :name  %>
  <p> Description: </p>
  <%= f.text_field  :desc %>
  <p> Deadline: </p>
  <%= f.date_field :deadline %>
  <%= f.submit "Add new project", class: "btn btn-primary" %>
<% end %>

<div>
  <a href="/" class="btn btn-default">Cancel</a>
</div>